"""empty message

Revision ID: 64c9ade17c7b
Revises: e8504a1f638d
Create Date: 2021-04-22 10:45:18.110607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c9ade17c7b'
down_revision = 'e8504a1f638d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('category', sa.String(length=64), nullable=False))
    op.add_column('todo', sa.Column('status', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'status')
    op.drop_column('todo', 'category')
    # ### end Alembic commands ###
